package remind

import (
	"testing"

	"github.com/gr1m0h/ichiza/internal/task"
)

func TestParseClosedIssues(t *testing.T) {
	out := []byte(`[
  {"title":"【〜10/25】会場最終確認","body":"event: ` + "`hiroshima-1`" + `\ndue: 2026-10-25\n\n_(generated by ichiza)_"},
  {"title":"手で作った Issue","body":"ichiza と無関係のメモ"},
  {"title":"【〜10/27】直前リマインド","body":"event: ` + "`hiroshima-1`" + `\r\ndue: 2026-10-27\r\n\r\nWeb UI 編集で CRLF になった本文"}
]`)
	closed, err := parseClosedIssues(out)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		taskKey("hiroshima-1", "2026-10-25", "会場最終確認"),
		taskKey("hiroshima-1", "2026-10-27", "直前リマインド"),
	}
	if len(closed) != len(want) {
		t.Fatalf("got %d keys, want %d: %v", len(closed), len(want), closed)
	}
	for _, k := range want {
		if !closed[k] {
			t.Errorf("missing key %q", k)
		}
	}
}

func TestParseClosedIssuesInvalidJSON(t *testing.T) {
	if _, err := parseClosedIssues([]byte("not json")); err == nil {
		t.Fatal("want error for invalid JSON")
	}
}

func TestCollectSkipsClosedIssues(t *testing.T) {
	eventsDir := t.TempDir()
	writeEventDir(t, eventsDir, "hiroshima-1", "SRE Lounge Hiroshima #1", "2026-10-30", "", []task.Task{
		{Title: "会場最終確認", Due: date(t, "2026-10-25")},
		{Title: "直前リマインド", Due: date(t, "2026-10-27")},
	})
	digests, err := Collect(Options{
		EventsDir: eventsDir, Now: date(t, "2026-10-27"), WindowDays: 7,
		ClosedIssues: map[string]bool{
			taskKey("hiroshima-1", "2026-10-25", "会場最終確認"): true,
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(digests) != 1 || len(digests[0].Items) != 1 {
		t.Fatalf("got %+v, want 1 digest with 1 item", digests)
	}
	if got := digests[0].Items[0].Task.Title; got != "直前リマインド" {
		t.Errorf("remaining task = %q, want 直前リマインド", got)
	}
}
