package scaffold

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/gr1m0h/ichiza/internal/config"
	"github.com/gr1m0h/ichiza/internal/event"
	"github.com/gr1m0h/ichiza/internal/lifecycle"
	"github.com/gr1m0h/ichiza/internal/task"
)

const tplSrc = `tasks:
  - title: 告知
    due: -7d
    labels: [announce]
  - title: 配信リハ
    due: -3d
    modes: [hybrid, online]
`

func setup(t *testing.T) (tplPath, baseDir string) {
	t.Helper()
	dir := t.TempDir()
	tplPath = filepath.Join(dir, "lifecycle.yaml")
	if err := os.WriteFile(tplPath, []byte(tplSrc), 0o644); err != nil {
		t.Fatal(err)
	}
	return tplPath, filepath.Join(dir, "events")
}

func TestRun(t *testing.T) {
	tpl, base := setup(t)
	res, err := Run(Options{
		Slug: "test-1", Title: "Test #1", Date: "2026-10-30", Mode: event.ModeHybrid,
		LifecyclePath: tpl, BaseDir: base, Config: config.Fallback(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Tasks) != 2 {
		t.Fatalf("got %d tasks, want 2 (hybrid)", len(res.Tasks))
	}

	e, err := event.Load(filepath.Join(res.Dir, "event.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if e.Event.Slug != "test-1" || e.Event.Mode != event.ModeHybrid {
		t.Errorf("event meta = %+v", e.Event)
	}
	if e.Venue == nil {
		t.Error("hybrid event should have a venue section")
	}
	if e.Streaming == nil {
		t.Error("hybrid event should have a streaming section")
	}

	tasks, err := task.Load(filepath.Join(res.Dir, "tasks.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if len(tasks) != 2 {
		t.Fatalf("tasks.yaml has %d tasks, want 2", len(tasks))
	}
	if got := tasks[0].Due.Format("2006-01-02"); got != "2026-10-23" {
		t.Errorf("first due = %s, want 2026-10-23", got)
	}
}

func TestRunOnsiteFiltersStreamingTasks(t *testing.T) {
	tpl, base := setup(t)
	res, err := Run(Options{
		Slug: "test-2", Title: "Test #2", Date: "2026-10-30", Mode: event.ModeOnsite,
		LifecyclePath: tpl, BaseDir: base, Config: config.Fallback(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Tasks) != 1 || res.Tasks[0].Title != "告知" {
		t.Errorf("onsite tasks = %+v, want only 告知", res.Tasks)
	}
}

func TestRunBadLifecyclePath(t *testing.T) {
	_, base := setup(t)
	_, err := Run(Options{
		Slug: "test-3", Title: "Test #3", Date: "2026-10-30", Mode: event.ModeOnsite,
		LifecyclePath: filepath.Join(base, "no-such.yaml"), BaseDir: base, Config: config.Fallback(),
	})
	if err == nil {
		t.Error("Run() with missing lifecycle = nil error, want error")
	}
}

func TestRunRejectsInvalidSlug(t *testing.T) {
	tpl, base := setup(t)
	for _, slug := range []string{"", "../escape", "UPPER", "has space", "日本語", "-leading", "a/b"} {
		_, err := Run(Options{
			Slug: slug, Title: "Test", Date: "2026-10-30", Mode: event.ModeOnsite,
			LifecyclePath: tpl, BaseDir: base, Config: config.Fallback(),
		})
		if err == nil {
			t.Errorf("Run() with slug %q = nil error, want error", slug)
		}
	}
}

func TestIssueBody(t *testing.T) {
	e := &event.Event{Event: event.Meta{Slug: "hiroshima-1", Date: "2026-10-30"}}
	tk := lifecycle.Task{Title: "告知", Due: mustDate(t, "2026-10-23")}

	body := issueBody(e, tk)
	for _, want := range []string{"hiroshima-1", "2026-10-23", "generated by ichiza"} {
		if !strings.Contains(body, want) {
			t.Errorf("issueBody should contain %q:\n%s", want, body)
		}
	}

	tk.Body = "手順はこちら"
	if body := issueBody(e, tk); !strings.Contains(body, "手順はこちら") {
		t.Errorf("custom body lost:\n%s", body)
	}
}

func mustDate(t *testing.T, s string) time.Time {
	t.Helper()
	d, err := time.Parse("2006-01-02", s)
	if err != nil {
		t.Fatal(err)
	}
	return d
}

func TestCreateIssues(t *testing.T) {
	var calls [][]string
	execCommand = func(name string, args ...string) *exec.Cmd {
		calls = append(calls, append([]string{name}, args...))
		return exec.Command("true")
	}
	t.Cleanup(func() { execCommand = exec.Command })

	tpl, base := setup(t)
	res, err := Run(Options{
		Slug: "test-4", Title: "Test #4", Date: "2026-10-30", Mode: event.ModeHybrid,
		LifecyclePath: tpl, BaseDir: base, Config: config.Fallback(), CreateIssues: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	// 1 milestone + 1 label (announce) + 1 issue per task
	if len(calls) != 2+len(res.Tasks) {
		t.Fatalf("got %d gh calls, want %d: %v", len(calls), 2+len(res.Tasks), calls)
	}
	if calls[0][1] != "api" || !strings.Contains(strings.Join(calls[0], " "), "milestones") {
		t.Errorf("first call should create milestone: %v", calls[0])
	}
	if got := strings.Join(calls[1], " "); got != "gh label create announce" {
		t.Errorf("second call should create label: %v", calls[1])
	}
	issue := strings.Join(calls[2], " ")
	if !strings.Contains(issue, "issue create") {
		t.Errorf("third call should create issue: %v", calls[2])
	}
	if !strings.Contains(issue, "【〜10/23】告知") {
		t.Errorf("issue title should embed deadline: %v", calls[2])
	}
	if !strings.Contains(issue, "--label announce") {
		t.Errorf("issue should carry labels: %v", calls[2])
	}
}

func TestCreateIssuesFailure(t *testing.T) {
	execCommand = func(name string, args ...string) *exec.Cmd {
		if len(args) > 0 && args[0] == "issue" {
			return exec.Command("false")
		}
		return exec.Command("true")
	}
	t.Cleanup(func() { execCommand = exec.Command })

	tpl, base := setup(t)
	_, err := Run(Options{
		Slug: "test-5", Title: "Test #5", Date: "2026-10-30", Mode: event.ModeOnsite,
		LifecyclePath: tpl, BaseDir: base, Config: config.Fallback(), CreateIssues: true,
	})
	if err == nil {
		t.Error("Run() with failing gh = nil error, want error")
	}
}

func TestRunRejectsExistingDir(t *testing.T) {
	tpl, base := setup(t)
	opt := Options{
		Slug: "dup", Title: "Dup", Date: "2026-10-30", Mode: event.ModeOnsite,
		LifecyclePath: tpl, BaseDir: base, Config: config.Fallback(),
	}
	if _, err := Run(opt); err != nil {
		t.Fatal(err)
	}
	if _, err := Run(opt); err == nil {
		t.Error("second Run() with same slug = nil error, want error")
	}
}
