// Package scaffold materializes a new event: directory, event.yaml,
// tasks.yaml, and (optionally) GitHub issues via the gh CLI.
package scaffold

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"

	"github.com/gr1m0h/ichiza/internal/config"
	"github.com/gr1m0h/ichiza/internal/event"
	"github.com/gr1m0h/ichiza/internal/lifecycle"
	"github.com/gr1m0h/ichiza/internal/task"
)

type Options struct {
	Slug          string
	Title         string
	Date          string // YYYY-MM-DD
	Mode          event.Mode
	LifecyclePath string // overrides config when non-empty
	BaseDir       string // overrides config when non-empty
	CreateIssues  bool
	Config        *config.Config
}

type Result struct {
	Dir   string
	Tasks []lifecycle.Task
}

// slug is used verbatim as a directory and branch name,
// so restrict its character set to prevent path traversal.
var validSlug = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*$`)

func Run(opt Options) (*Result, error) {
	if !validSlug.MatchString(opt.Slug) {
		return nil, fmt.Errorf("invalid slug %q: must match %s", opt.Slug, validSlug)
	}
	cfg := opt.Config
	if cfg == nil {
		cfg = config.Fallback()
	}
	if opt.BaseDir == "" {
		opt.BaseDir = cfg.EventsDir
	}
	if opt.LifecyclePath == "" {
		opt.LifecyclePath = cfg.Lifecycle
	}
	dir := filepath.Join(opt.BaseDir, opt.Slug)
	if _, err := os.Stat(dir); err == nil {
		return nil, fmt.Errorf("%s already exists", dir)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	venue := cfg.Defaults.Venue
	e := event.Skeleton(opt.Slug, opt.Title, opt.Date, opt.Mode, event.SkeletonDefaults{
		Venue:         &venue,
		Roles:         cfg.Defaults.Roles,
		Streaming:     cfg.Defaults.Streaming,
		Timetable:     cfg.Defaults.Timetable,
		StreamingRole: cfg.Defaults.StreamingRole,
	})
	if err := e.Save(filepath.Join(dir, "event.yaml")); err != nil {
		return nil, err
	}

	tpl, err := lifecycle.LoadTemplate(opt.LifecyclePath)
	if err != nil {
		return nil, err
	}
	tasks, err := lifecycle.Expand(tpl, e)
	if err != nil {
		return nil, err
	}
	if err := saveTasks(filepath.Join(dir, "tasks.yaml"), tasks); err != nil {
		return nil, err
	}

	if opt.CreateIssues {
		if err := createIssues(e, tasks); err != nil {
			return nil, fmt.Errorf("create issues: %w", err)
		}
	}
	return &Result{Dir: dir, Tasks: tasks}, nil
}

func saveTasks(path string, tasks []lifecycle.Task) error {
	docs := make([]task.Task, 0, len(tasks))
	for _, t := range tasks {
		docs = append(docs, task.Task{Title: t.Title, Due: t.Due, Labels: t.Labels})
	}
	return task.Save(path, docs)
}

// execCommand is swapped in tests so createIssues can run without gh.
var execCommand = exec.Command

// createIssues shells out to gh so we need no API client or token plumbing.
// One milestone per event, one issue per task with the deadline in the title.
func createIssues(e *event.Event, tasks []lifecycle.Task) error {
	milestone := e.Event.Title
	// Best effort: milestone may already exist.
	_ = execCommand("gh", "api", "-X", "POST",
		"repos/{owner}/{repo}/milestones",
		"-f", "title="+milestone,
		"-f", "due_on="+e.Event.Date+"T00:00:00Z",
	).Run()

	for _, t := range tasks {
		args := []string{
			"issue", "create",
			"--title", fmt.Sprintf("【〜%s】%s", t.Due.Format("01/02"), t.Title),
			"--body", issueBody(e, t),
			"--milestone", milestone,
		}
		for _, l := range t.Labels {
			args = append(args, "--label", l)
		}
		cmd := execCommand("gh", args...)
		cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("issue %q: %w", t.Title, err)
		}
	}
	return nil
}

func issueBody(e *event.Event, t lifecycle.Task) string {
	body := t.Body
	if body == "" {
		body = "_(generated by ichiza)_"
	}
	return fmt.Sprintf("event: `%s`\ndue: %s\n\n%s",
		e.Event.Slug, t.Due.Format("2006-01-02"), body)
}
